name: "TSQLLint Action"
author: "lowlydba"
description: "Lint T-SQL files using TSQLLint"
branding:
  icon: "check-circle"
  color: "green"
inputs:
  path:
    description: "Space delimited path(s) to run linter against. Wildcards can be specified using `*`."
    required: false
    default: "."
  config:
    description: "Path to a configuration file for the linter."
    required: false
  comment:
    description: "Create comment with summary of linter results."
    required: false
    default: "false"
  only_changed_files:
    description: "Only lint on modified `.sql` files. Will ignore `path` if `true` in pull requests, or default back to `path` if not in a pull request."
    required: false
    default: "false"
runs:
  using: composite
  steps:
    - name: Install TSQLLint
      run: |
        yarn global add tsqllint > /dev/null 2>&1
      shell: bash

    - name: Run TSQLLint
      run: |
        tsqllint -p -c "${{ inputs.config }}" | tail -1
        tsqllint -v | tail -1
        if [ "${{ inputs.only_changed_files }}" == "true" ] && [ $GITHUB_HEAD_REF != "" ]
          then files=`git diff --diff-filter=M --name-only origin/$GITHUB_BASE_REF...origin/$GITHUB_HEAD_REF | grep -E '\.(sql)$'`;
          else files=`echo "${{ inputs.path }}"`;
        fi
        tsqllint $files -c "${{ inputs.config }}" > .tsqllint-output;
        # Save return code status
        tsqllint_rc=$?
        echo "tsqllint_rc=$tsqllint_rc" >> $GITHUB_ENV
        # Parse results
        cat .tsqllint-output
      shell: bash {0}

    - name: Parse results
      run: |
        warnings=`cat .tsqllint-output | tail -1`
        errors=`cat .tsqllint-output | tail -2 | head -1`
        if [ $tsqllint_rc == 0 ];
          then status=":white_check_mark:" && summary="No issues found.";
          else status=":x:" && summary=`cat .tsqllint-output | tail -4`;
        fi
        # Build comment
        echo -e "## $status TSQLLint Summary\n" >> .tsqllint-output.final
        echo -e "$summary" >> .tsqllint-output.final
        echo -e "\n[Detailed results.]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID)" >> .tsqllint-output.final
        echo -e "\n:recycle: This comment has been updated with latest results." >> .tsqllint-output.final
      shell: bash

    - name: Post as comment
      if: contains(inputs.comment, 'true') && github.event.number != 0
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        path: .tsqllint-output.final

    - name: Set final status
      if: contains(env.tsqllint_rc, 1)
      run: exit 1
      shell: bash
