---
name: "TSQLLint Action"
author: "lowlydba"
description: "Lint T-SQL files using TSQLLint"
branding:
  icon: "check-circle"
  color: "green"
inputs:
  path:
    description: "Space delimited path(s) to run linter against. Wildcards can be specified using `*`."
    required: false
    default: "."
  config:
    description: "Path to a configuration file for the linter."
    required: false
    default: ".github/linters/.tsqllintrc"
  comment:
    description: "Create comment with summary of linter results."
    required: false
    default: "false"
  only-changed-files:
    description: "Only lint on modified `.sql` files. Will ignore `path` if `true` in pull requests, or default back to `path` if not in a pull request."
    required: false
    default: "false"
  append-comment:
    description: "Append results from multiple runs in a single comment."
    required: false
    default: "false"
  summary:
    description: "Add linter results to the job summary."
    required: false
    default: "false"
  compare-branch:
    description: "Branch to diff against when using only-changed-files."
    required: false
    default: "main"

runs:
  using: composite
  steps:
    - name: Install TSQLLint
      run: |
        npm i -g tsqllint | Out-Null
      shell: pwsh

    - name: "Run TSQLLint"
      run: |
        $params = @{
          Config = "${{ inputs.config }}"
          OnlyChangedFiles = "${{ inputs.only-changed-files }}"
          Path = "${{ inputs.path }}"
          Branch = "${{ inputs.compare-branch }}"
        }
        ${{ github.action_path }}/main.ps1 @params
      shell: pwsh

    - name: Post comment
      if: ${{ inputs.comment == 'true' && env.no_results != 'true' }}
      uses: marocchino/sticky-pull-request-comment@v2.9.3
      with:
        path: ${{ env.COMMENT_FILE }}
        append: ${{ inputs.append-comment }}
        header: tsqllint-action

    - name: Post Job summary
      if: ${{ inputs.summary == 'true' && env.no_results != 'true' }}
      run: |
        Get-Content -Path ${{ env.COMMENT_FILE }} >> $env:GITHUB_STEP_SUMMARY
      shell: pwsh

    - name: Exit
      if: contains(env.tsqllint_rc, 1)
      run: exit 1
      shell: pwsh
